version: "3.9"
services:
  web:
    build: ./main_app
    ports:
      - "8000:8000"
  html:
    build: ../gavno/html
    ports:
      - "9090:9090"
    depends_on:
      - web

  nginx:
    container_name: nginx
    restart: always
    build: ../gavno/nginx
    ports:
      - "80:80"
    depends_on:
      - html
      - web
